"""Add avatar_url to users table

Revision ID: 55dc53a266c1
Revises: 5ce3d52b1ac6
Create Date: 2026-02-10 02:59:16.392780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55dc53a266c1'
down_revision: Union[str, Sequence[str], None] = '5ce3d52b1ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.create_foreign_key('fk_user_selected_repo', 'users', 'repositories', ['selected_repo_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_selected_repo', 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
