"""craete users repositories devlog table

Revision ID: d200cd51a476
Revises: a7e83e692bbf
Create Date: 2026-01-18 04:33:03.232049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd200cd51a476'
down_revision: Union[str, Sequence[str], None] = 'a7e83e692bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_username', sa.String(length=100), nullable=False),
    sa.Column('github_user_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=500), nullable=False),
    sa.Column('selected_repo_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['selected_repo_id'], ['repositories.id'], name='fk_user_selected_repo', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_user_id'),
    sa.UniqueConstraint('github_username')
    )
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repo_name', name='uq_user_repo')
    )
    op.create_index('ix_repo_user_selected', 'repositories', ['user_id', 'is_selected'], unique=False)
    op.create_table('devlogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('main_tasks', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('learned_things', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.Column('raw_commits', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repository_id', 'date', name='uq_user_repo_date')
    )
    op.create_index(op.f('ix_devlogs_date'), 'devlogs', ['date'], unique=False)
    op.create_index('ix_user_date', 'devlogs', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_date', table_name='devlogs')
    op.drop_index(op.f('ix_devlogs_date'), table_name='devlogs')
    op.drop_table('devlogs')
    op.drop_index('ix_repo_user_selected', table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('users')
    # ### end Alembic commands ###
